// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdwdvzmdmygqzvrnfbts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd2R2em1kbXlncXp2cm5mYnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczMDIwMTYsImV4cCI6MjA1Mjg3ODAxNn0.AnsmqKG0k1dn4QtjMVKpUcYMaTX4OLpc0TwDe5-5Vgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);